---
apiVersion: v1
kind: Pod
metadata:
  name: test-sriov-ib-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: example-sriov-ib-network
spec:
  containers:
    - name: test-sriov-ib-pod
      image: mellanox/centos_7_4_mofed_4_2_1_2_0_0_60
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -
        - sleep inf
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
      resources:
        requests:
          nvidia.com/mlnxnics: "1"
        limits:
          nvidia.com/mlnxnics: "1"
