apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-downloader
  namespace: cpod
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cpod
  name: role-downloader
rules:
- apiGroups: ["cpod"]
  resources: ["datasetstorages" , "modelstorages"]
  verbs: ["*"]
- apiGroups: ["cpod"]
  resources: ["datasetstorages/status" , "modelstorages/status"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binding-downloader
subjects:
  - kind: ServiceAccount
    name: sa-downloader
    namespace: cpod
roleRef:
  kind: ClusterRole
  name: role-downloader
  apiGroup: rbac.authorization.k8s.io
