apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: shared-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  csi:
    driver: csi.juicefs.com
    nodePublishSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system
    volumeHandle: shared-pv
  mountOptions:
  - subdir=/
  persistentVolumeReclaimPolicy: Retain
  storageClassName: juicefs-sc
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
  finalizers:
  - kubernetes.io/pvc-protection
  name: shared-pvc
  namespace: public
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  volumeName: shared-pv
