apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: dp-mpijob
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: swr.cn-east-3.myhuaweicloud.com/sxwl/cifards:v0.0.1
            name: deepspeed-mpijob-container
            command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "2"
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - python3
            - /deepspeed/DeepSpeedExamples/training/cifar/cifar10_deepspeed.py
            - --deepspeed_mpi
            - --deepspeed
            - --deepspeed_config
            - /deepspeed/DeepSpeedExamples/training/cifar/ds_config.json
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: swr.cn-east-3.myhuaweicloud.com/sxwl/cifards:v0.0.1
            name: deepspeed-mpijob-container
            resources:
              limits:
                nvidia.com/gpu: 8
