apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: dp-mpijob
spec:
  slotsPerWorker: 2
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          volumes:
            - name: mpi-storage
              persistentVolumeClaim:
                claimName: mpi-data-pvc
          containers:
          - image: swr.cn-east-3.myhuaweicloud.com/sxwl/cifards:v0.0.6
            name: deepspeed-mpijob-container
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: "/deepspeed/DeepSpeedExamples/training/cifar/data"
                name: mpi-storage
            command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "3"
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DISABLE_P2P=0
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - mpi_warn_on_fork 
            - "0"
            - python3
            - /deepspeed/DeepSpeedExamples/training/cifar/cifar10_deepspeed.py
            - --deepspeed_mpi
            - --deepspeed
            - --deepspeed_config
            - /deepspeed/DeepSpeedExamples/training/cifar/ds_config.json
    Worker:
      replicas: 3
      template:
        spec:
          volumes:
            - name: mpi-storage
              persistentVolumeClaim:
                claimName: mpi-data-pvc 
          containers:
          - image: swr.cn-east-3.myhuaweicloud.com/sxwl/cifards:v0.0.6
            name: deepspeed-mpijob-container
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                nvidia.com/gpu: 2
            volumeMounts:
              - mountPath: "/deepspeed/DeepSpeedExamples/training/cifar/data"
                name: mpi-storage
