{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc }}
  mysql-user: {{ .Values.mysql.user | b64enc }}
  mysql-password: {{ .Values.mysql.password | b64enc }}
  mysql-database: {{ .Values.mysql.database | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: go-gateway-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  gateway_dsn: {{ .Values.gateway.dsn | b64enc }}
  auth_secret: {{ .Values.gateway.authSecret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: go-scheduler-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  scheduler_dsn: {{ .Values.scheduler.dsn | b64enc }}
  admin_access_id: {{ .Values.scheduler.adminAccessId | b64enc }}
  admin_access_key: {{ .Values.scheduler.adminAccessKey | b64enc }}
  upload_access_id: {{ .Values.scheduler.uploadAccessId | b64enc }}
  upload_access_key: {{ .Values.scheduler.uploadAccessKey | b64enc }}
{{- end }}
