apiVersion: v1
kind: Pod
metadata:
  name: exporter
  namespace: gpu-operator
spec:
  containers:
  - image: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/exporter:latest 
    imagePullPolicy: Always
    name: main
    ports:
    - containerPort: 9400
      name: metrics
      protocol: TCP
    resources: 
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/kubelet/pod-resources
      name: pod-gpu-resources
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
  runtimeClassName: nvidia
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /var/lib/kubelet/pod-resources
      type: ""
    name: pod-gpu-resources