apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-agent
  template:
    metadata:
      labels:
        app: weather-agent
    spec:
      containers:
        - name: weather-agent
          image: dockerhub.kubekey.local/kubesphereio/weather-agent:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: WEATHER_KEY
              value: ""
            - name: LLM_URL
              value: ""