FROM registry.cn-hangzhou.aliyuncs.com/sxwl-ai/common:v2023-10-16-00

# Use China mainland pip source
RUN python3 -m pip config set global.index-url \
    https://pypi.tuna.tsinghua.edu.cn/simple && \
    python3 -m pip install --no-cache-dir --upgrade pip

ADD . /workspace

WORKDIR /workspace

RUN python3 -m pip install -r requirements.txt
