package common

// NO_TEST_NEEDED

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type CodJobInfo struct {
	// Market Portal generates this ID
	JobId     string `json:"job_id"`

	// Market manager generates this ID
	CpodJobId string `json:"cpod_job_id"`

	// Cpod ID generated by Cpod manager
	CpodId    string `json:"cpod_job_id"`

	// Job execution result: 0 success, 1 failed
	State     int    `json:"state"`

	// JobUrl points to the link to the results produces
	// Should be called Job result URL.
	JobUrl    string `json:"job_url"`
}

type CpodResourceInfos struct {
	Cpods []CpodResourceInfo `json:"cpods"`
}

type CpodResourceInfo struct {
	GroupId  string  `json:"group_id,omitempty"`
	CpodId   string  `json:"cpod_id"`
	GpuTotal float32 `json:"gpu_total"`
	GpuUsed  float32 `json:"gpu_used"`
	GpuFree  float32 `json:"gpu_free"`
}
