kubeStateMetrics:
  enabled: true

grafana:
  enabled: true
  image:
    repository: dockerhub.kubekey.local/kubesphereio/grafana
  sidecar:
    image:
      repository: dockerhub.kubekey.local/kubesphereio/k8s-sidecar
  initChownData:
    image:
      repository: dockerhub.kubekey.local/kubesphereio/busybox
  testFramework:
    image: dockerhub.kubekey.local/kubesphereio/bats
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki-stack.loki-stack.svc.cluster.local:3100
        access: proxy
        isDefault: false

kube-state-metrics:
  image:
    registry: dockerhub.kubekey.local/kubesphereio
    repository: kube-state-metrics

prometheus-node-exporter:
  image:
    registry: dockerhub.kubekey.local/kubesphereio
    repository: node-exporter

global:
  imageRegistry: dockerhub.kubekey.local/kubesphereio

alertmanager:
  alertmanagerSpec:
    image:
      registry: dockerhub.kubekey.local/kubesphereio
      repository: alertmanager

prometheusOperator:
  image:
    registry: dockerhub.kubekey.local/kubesphereio
    repository: prometheus-operator
  admissionWebhooks:
    patch:
      image:
        registry: dockerhub.kubekey.local/kubesphereio
        repository: kube-webhook-certgen
  prometheusConfigReloader:
    image:
      registry: dockerhub.kubekey.local/kubesphereio
      repository: prometheus-config-reloader
  thanosImage:
    registry: dockerhub.kubekey.local/kubesphereio
    repository: thanos

prometheus:
  prometheusSpec:
    image:
      registry: dockerhub.kubekey.local/kubesphereio
      repository: prometheus
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: gpu-metrics
        scrape_interval: 1s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - gpu-operator
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: node_hostname
      - job_name: infiniband-exporter
        scrape_interval: 30s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - network-operator
        static_configs:
          - targets: ['infiniband-exporter.network-operator.svc.cluster.local:9683']

thanosRuler:
  thanosRulerSpec:
    image:
      registry: dockerhub.kubekey.local/kubesphereio
      repository: thanos
