apiVersion: v1
kind: Pod
metadata:
  name: bert-cpu
spec:
  restartPolicy: Never
  containers:
    - name: bert-container
      image: swr.cn-east-3.myhuaweicloud.com/sxwl/train_bert_deepspeed:v1
      imagePullPolicy: IfNotPresent
      args:
        - python3
        - train_bert.py
        - --checkpoint_dir
        - ./experiments/single/
