# cuda_base was built from base.Dockerfile
# You must change this to the right one you built from base.Dockerfile
FROM registry.ap-southeast-1.aliyuncs.com/sxwl-ai/cuda_base:2023-10-23
WORKDIR /workspace
COPY *.py ./
COPY model_roberta_base ./model_roberta_base
