---
apiVersion: v1
kind: Service
metadata:
  name: infiniband-exporter
  namespace: network-operator
spec:
  selector:
    app: infiniband-exporter
  ports:
    - protocol: TCP
      port: 9683
      targetPort: 9683
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infiniband-exporter
  namespace: network-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infiniband-exporter
  template:
    metadata:
      labels:
        app: infiniband-exporter
    spec:
      nodeSelector:
        "feature.node.kubernetes.io/rdma.available": "true"
      containers:
      - name: infiniband-exporter
        image: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/infiniband-exporter:main
        securityContext:
          privileged: true
          capabilities:
            add: [ "IPC_LOCK" ]
