kubeStateMetrics:
  enabled: true

grafana:
  enabled: true
  image:
    repository: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/grafana
  sidecar:
    image:
      repository: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/k8s-sidecar
  initChownData:
    image:
      repository: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/busybox
  testFramework:
    image: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/bats
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki-stack.loki-stack.svc.cluster.local:3100
        access: proxy
        isDefault: false
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: "Main Org."
      org_role: Viewer
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: juicefs-sc
    accessMode: ReadWriteOnce

kube-state-metrics:
  image:
    registry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai
    repository: kube-state-metrics

prometheus-node-exporter:
  image:
    registry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai
    repository: node-exporter

global:
  imageRegistry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai

alertmanager:
  alertmanagerSpec:
    image:
      registry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai
      repository: alertmanager

prometheusOperator:
  image:
    registry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai
    repository: prometheus-operator
  admissionWebhooks:
    patch:
      image:
        registry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai
        repository: kube-webhook-certgen
  prometheusConfigReloader:
    image:
      registry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai
      repository: prometheus-config-reloader
  thanosImage:
    registry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai
    repository: thanos

prometheus:
  prometheusSpec:
    image:
      registry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai
      repository: prometheus
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: gpu-metrics
        scrape_interval: 1s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - gpu-operator
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: node_hostname
      - job_name: infiniband-exporter
        scrape_interval: 30s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - network-operator
        static_configs:
          - targets: ['infiniband-exporter.network-operator.svc.cluster.local:9683']

thanosRuler:
  thanosRulerSpec:
    image:
      registry: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai
      repository: thanos
