apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-torchrun
  namespace: training-operator
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: dockerhub.kubekey.local/kubesphereio/modelscope_gpt3:v002
              imagePullPolicy: Always
              command:
                - "torchrun"
                - "--nproc_per_node=1"
                - "finetune_poetry.py"