# 单机八卡训练基于gpt3-1.3b 续写模型
apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-torchrun
  namespace: training-operator
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: registry.cn-beijing.aliyuncs.com/sxwl-ai/modelscope_gpt3_1h8g2dp:latest
              imagePullPolicy: Always
              resources:
                limits:
                  nvidia.com/gpu: 8
              command:
                - "torchrun"
                - "--nproc_per_node=8"
                - "finetune_poetry.py"
              volumeMounts:
                - name: dataset
                  mountPath: /workspace/chinese-poetry-collection
                - name: pretrained-model
                  mountPath: /workspace/nlp_gpt3_text-generation_1.3B
                - name: saved-model
                  mountPath: /workspace/gpt3_poetry
                - name: shm
                  mountPath: /dev/shm
          volumes:
            - name: dataset
              persistentVolumeClaim:
                claimName: dataset
                readOnly: false
            - name: pretrained-model
              persistentVolumeClaim:
                claimName: pretrained-model
                readOnly: false
            - name: saved-model
              persistentVolumeClaim:
                claimName: saved-model
                readOnly: false
            - name: shm
              emptyDir:
                medium: Memory
                sizeLimit: 5120Mi