---
# Config file for golangci-lint, placed here so local run of golangci-lint
# can find this config file.
#
# Super-linter uses a symbol-linked file under .github/linter/.golangci.yml
run:
  allow-parallel-runners: true
  timeout: 6m
  skip-dirs:
    - .github
    - devops
    - examples
    - home
    - k8s

output:
  sort-results: true

# Configurations are at:
# https://golangci-lint.run/usage/configuration/#issues-configuration
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  # It's a super-useful option for integration of golangci-lint into existing large codebase.
  # It's not practical to fix all existing issues at the moment of integration:
  # much better don't allow issues in new code.
  #
  # Default: false.
  new: true
  # Fix found issues (if it's supported by the linter).
  fix: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - godot
    - gofumpt
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nolintlint
    - nonamedreturns
    - predeclared
    - staticcheck
    - stylecheck
    - unused
    - lll
    - whitespace
    - goimports
    - revive
    # depguard checks imports are from specified repos/packages, that is too
    # restrictive for rapid prototyping, so we disabled it.
    # - depguard

linters-settings:
  errcheck:
    check-type-assertions: true
  goimports:
    local-prefixes: github.com/tricorder
  nakedret:
    max-func-lines: 0
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#package-comments
      - name: package-comments
        severity: error
        disabled: false
      - name: argument-limit
        severity: error
        disabled: false
        # TODO(yzhao): Reduce it to 5
        arguments: [8]
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
      - name: exported
        severity: error
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # Tab width in spaces.
    tab-width: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by github.com/tricorder/src/utils/log, 
      # logrus is allowed to use only in log package
      - github.com/sirupsen/logrus
    ignore-file-rules:
      - "**/utils/log/*.go"
  staticcheck:
    # Deprecated: use the global `run.go` instead.
    go: "1.21.1"
    # SAxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    # Default: ["*"]
    checks: ["all"]
  stylecheck:
    # Deprecated: use the global `run.go` instead.
    go: "1.21.1"
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    # Default: ["*"]
    # ST1003 is for enforcing camel case.
    checks: ["all", "-ST1003"]
