apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      containers:
        - name: rag-service
          image: dockerhub.kubekey.local/kubesphereio/rag-service:v0.0.6
          ports:
            - containerPort: 5000
          env:
            - name: https_proxy
              value: "http://squid:squid@214.2.5.239:13128"
            - name: http_proxy
              value: "http://squid:squid@214.2.5.239:13128"
            - name: no_proxy
              value: "localhost,127.0.0.1,openchat.llm.sxwl.ai,10.233.57.192,10.233.52.22"
            - name: MILVUS_HOST
              value: "10.233.52.22"
            - name: MILVUS_PORT
              value: "19530"
            - name: OPENCHAT_URL
              value: "http://10.233.57.192/v1/chat/completions"
