apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-portalsynch
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-portalsynch
rules:
- apiGroups:
  - cpod.cpod
  resources:
  - cpodjobs
  - inferences
  - datasetstorages
  - modelstorages
  - finetunes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - cpodjobs/status
  - inferences/status
  verbs:
  - get
- apiGroups:
  - cpod.cpod
  resources:
  - datasetstorages
  - datasetstorages/status
  - modelstorages
  - modelstorages/status
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portalsynch-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sa-portalsynch
  namespace: cpod-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalsynch
  namespace: system
  labels:
    control-plane: portalsynch
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: portalsynch
    app.kubernetes.io/component: portalsynch
    app.kubernetes.io/created-by: cpodjob
    app.kubernetes.io/part-of: cpodjob
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: portalsynch
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: portalsynch
      labels:
        control-plane: portalsynch
    spec:
      containers:
      - name: portalsynch
        env:
        - name: DEPLOY
          value: DEBUG
        - name: ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: access_key
              name: cpod-info
        - name: CPOD_ID
          valueFrom:
            configMapKeyRef:
              key: cpod_id
              name: cpod-info
        - name: STORAGECLASS
          valueFrom:
            configMapKeyRef:
              key: storage_class
              name: cpod-info
        - name: API_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: api_address
              name: cpod-info
        image: portalsynch:latest
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: sa-portalsynch
      terminationGracePeriodSeconds: 10