# We are using MPI Operator V2, might need to be reverted to V1
# Uncomment this to use the V1 training operator
# apiVersion: kubeflow.org/v1
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: dp-mpijob-bert
spec:
  slotsPerWorker: 4
  runPolicy:
    # Keep pods around after termination
    cleanPodPolicy: None
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          hostIPC: True
          containers:
          - image: sxwl.harbor.com/sxwl-1/bert:v10jim
            name: deepspeed-mpijob-container
            imagePullPolicy: IfNotPresent
            command:
            - mpirun
            - -np
            - "12"
            - --allow-run-as-root
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - NCCL_P2P_DISABLE=1
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - mpi_warn_on_fork
            - "0"
            - python3
            - train_bert_ds_original.py
            - --checkpoint_dir
            - ./ds_experiments
            - --deepspeed_mpi
            - --deepspeed
    Worker:
      replicas: 3
      template:
        spec:
          hostIPC: True
          containers:
          - image: sxwl.harbor.com/sxwl-1/bert:v10jim
            name: deepspeed-mpijob-container
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                nvidia.com/gpu: 4
