# We are using MPI Operator V2, might need to be reverted to V1
# Uncomment this to use the V1 training operator
# apiVersion: kubeflow.org/v1
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: dp-mpijob-bert
spec:
  slotsPerWorker: 2
  runPolicy:
    # Keep pods around after termination
    cleanPodPolicy: None
  # See LauncherCreationPolicy in
  # https://github.com/kubeflow/mpi-operator/tree/master
  # This prevents launcher repetitive restart.
  launcherCreationPolicy: "WaitForWorkersReady"
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          hostIPC: True
          containers:
          - image: dockerhub.kubekey.local/kubesphereio/sxwl-ai/bert:with-dataset-2
            name: bert-launcher
            imagePullPolicy: Always
            command:
            - mpirun
            - -np
            - "4"
            - --allow-run-as-root
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - NCCL_P2P_DISABLE=1
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - mpi_warn_on_fork
            - "0"
            - python3
            - train_bert_ds.py
            - --checkpoint_dir
            - ds-experiments
            - --dataset_dir
            - dataset1/wikitext
            - --deepspeed_mpi
            - --deepspeed
            - --num_iterations=200
    Worker:
      replicas: 2
      template:
        spec:
          hostIPC: True
          nodeSelector:
            nvidia.com/gpu.product: NVIDIA-GeForce-RTX-3090
          containers:
          - image: dockerhub.kubekey.local/kubesphereio/sxwl-ai/bert:with-dataset-2
            name: bert-ds-worker
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /workspace/dataset1
              name: dataset1
            - mountPath: /workspace/ds-experiments
              name: ckpt-pv
            resources:
              limits:
                nvidia.com/gpu: 2
          volumes:
          - name: dataset1
            cephfs:
              monitors:
              - 10.233.33.169:6789
              # CephFS' internal path
              path: /hf/dataset1
              user: admin
              secretRef:
                name: ceph-secret
              readOnly: true
          - name: ckpt-pv
            cephfs:
              monitors:
              - 10.233.33.169:6789
              path: /readwrite
              user: admin
              secretRef:
                name: ceph-secret
              readOnly: false
