# We are using MPI Operator V2, might need to be reverted to V1
# Uncomment this to use the V1 training operator
# apiVersion: kubeflow.org/v1
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: dp-mpijob-bert
spec:
  slotsPerWorker: 2
  runPolicy:
    # Keep pods around after termination
    cleanPodPolicy: None
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          hostIPC: True
          containers:
          - image: dockerhub.kubekey.local/kubesphereio/sxwl-ai/bert:2023-10-24
            name: bert-launcher
            imagePullPolicy: IfNotPresent
            command:
            - mpirun
            - -np
            - "4"
            - --allow-run-as-root
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - NCCL_P2P_DISABLE=1
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - mpi_warn_on_fork
            - "0"
            - python3
            - train_bert_ds.py
            - --checkpoint_dir
            - ./ds_experiments
            - --datasets_dir
            - dataset/wikitext
            - --deepspeed_mpi
            - --deepspeed
    Worker:
      replicas: 2
      template:
        spec:
          hostIPC: True
          nodeSelector:
            nvidia.com/gpu.product: NVIDIA-GeForce-RTX-3090
          containers:
          - image: dockerhub.kubekey.local/kubesphereio/sxwl-ai/bert:2023-10-24
            name: bert-ds-worker
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                nvidia.com/gpu: 2
