apiVersion: v1
kind: Pod
metadata:
  name: bert-gpu
spec:
  restartPolicy: Never
  containers:
    - name: bert-container
      image: swr.cn-east-3.myhuaweicloud.com/sxwl/train_bert_deepspeed:v1
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
      imagePullPolicy: IfNotPresent
      args:
        - python3
        - train_bert.py
        - --local_rank 
        - "0"
        - --checkpoint_dir
        - ./experiments/single/
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedul
