apiVersion: cpod.cpod/v1beta1
kind: JupyterLab
metadata:
  labels:
    app.kubernetes.io/name: jupyterlab
    app.kubernetes.io/instance: jupyterlab-sample
    app.kubernetes.io/part-of: cpodjob
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cpodjob
  name: jupyterlab-sample
spec:
  # TODO(user): Add fields here
