---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: cpod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: tensorboard
  namespace: cpod
  labels:
    app: tensorboard
spec:
  type: NodePort
  ports:
  - port: 6006
    targetPort: 6006
    nodePort: 30013
  selector:
    app: tensorboard
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorboard
  namespace: cpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard
  template:
    metadata:
      labels:
        app: tensorboard
    spec:
      containers:
      - name: tensorboard
        image: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/tensorflow:latest
        command: ["tensorboard", "--logdir", "/logs", "--host", "0.0.0.0"]
        ports:
        - containerPort: 6006
        volumeMounts:
        - name: log-volume
          mountPath: /logs
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: logs
