# We are using MPI Operator V2, might need to be reverted to V1
# Uncomment this to use the V1 training operator
# apiVersion: kubeflow.org/v1
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: dp-mpijob-bert
spec:
  slotsPerWorker: 2
  runPolicy:
    # `Running` pods are deleted, which keeps `completed` pods.
    # Since worker pods do not have logs, we only need to keep completed pods,
    # which is the launcher pod (exactly what we like).
    cleanPodPolicy: Running
  # See LauncherCreationPolicy in
  # https://github.com/kubeflow/mpi-operator/tree/master
  # This prevents launcher repetitive restart.
  launcherCreationPolicy: WaitForWorkersReady
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          hostIPC: True
          containers:
          - image: registry.cn-beijing.aliyuncs.com/sxwl-ai/bert:latest
            name: launcher
            imagePullPolicy: Always
            command:
            - mpirun
            - -np
            - "4"
            - --allow-run-as-root
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - NCCL_P2P_DISABLE=1
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - mpi_warn_on_fork
            - "0"
            - python3
            - train_bert_ds.py
            - --checkpoint_dir
            - ds-experiments
            - --dataset_dir
            - dataset/wikitext
            - --num_iterations=50
    Worker:
      replicas: 2
      template:
        spec:
          hostIPC: True
          nodeSelector:
            nvidia.com/gpu.product: NVIDIA-GeForce-RTX-3090
          containers:
          - image: registry.cn-beijing.aliyuncs.com/sxwl-ai/bert:latest
            name: worker
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /workspace/ds-experiments
              name: ckpt-pv
            - mountPath: /workspace/saved-model
              name: saved-model-pv
            resources:
              limits:
                nvidia.com/gpu: 2
          volumes:
          - name: ckpt-pv
            persistentVolumeClaim:
              claimName: ckpt
              readOnly: false
          - name: saved-model-pv
            persistentVolumeClaim:
              claimName: saved-model
              readOnly: false
