apiVersion: v1
kind: Pod
metadata:
  name: bert-ds-gpu-01
spec:
  restartPolicy: Never
  hostIPC: True
  containers:
    - name: bert-ds-container
      image: swr.cn-east-3.myhuaweicloud.com/sxwl/train_bert_deepspeed:v2
      resources:
        limits:
          nvidia.com/gpu: 8
      imagePullPolicy: IfNotPresent
      args:
        - deepspeed
        - --master_port
        - "6000"
          #- --num_gpus
          #- "2"
        - train_bert_ds.py
        - --checkpoint_dir
        - ./ds_experiments
      env:
      - name: NCCL_P2P_DISABLE
        value: "1"
      - name: NCCL_DEBUG
        value: "INFO"
      - name: NCCL_IB_DISABLE
        value: "1"
        #- name: NCCL_NET_PLUGIN
        #value: "none"
        #- name: NCCL_NET
        # value: "IB"
        #- name: NCCL_SOCKET_IFNAME
        #value: "tunl0"
        #- name: NCCL_IB_TC 
        #value: "128"
        #- name: NCCL_IB_GID_INDEX
        #value: "3"
        #- name: NCCL_IB_TIMEOUT
        #value: "22"
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
