apiVersion: cpod.sxwl.ai/v1
kind: ModelStorage
metadata:
  name: model-storage-58c268c6ee50f996
  namespace: cpod
spec:
  modeltype: huggingface
  modelname: fka/awesome-chatgpt-prompts
  pvc: pvc-model-58c268c6ee50f996
status:
  phase: downloading