apiVersion: cpod.sxwl.ai/v1
kind: ModelStorage
metadata:
  name: modelstorage-sample
  namespace: cpod
spec:
  modeltype: huggingface
  modelname: https://huggingface.co/fka/awesome-chatgpt-prompts
  pvc: pvc1