{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cpod-info
  namespace: {{ .Values.namespace }}
data:
  access_key: {{ .Values.sxcloud.accessKey | quote }}
  api_address: {{ .Values.sxcloud.apiAddress | quote }}
  cpod_id: {{ .Values.sxcloud.cpodId| quote }}
  log_level: {{ .Values.sxcloud.logLevel | quote }}
  oss_bucket: {{ .Values.sxcloud.ossBucket | quote }}
  storage_class: {{ .Values.sxcloud.storageClass | quote }}
{{- end }}
