{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cpodjob
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: cpodjob
    control-plane: controller-manager
  name: cpod-controller-manager
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: {{ .Values.cpodoperator.rbacProxy.image }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --storageClassName={{ .Values.cpodoperator.manager.args.storageClassName }}
        - --oss-ak={{ .Values.cpodoperator.manager.args.oss.ak }}
        - --oss-as={{ .Values.cpodoperator.manager.args.oss.as }}
        - --jupyterlab-image={{ .Values.cpodoperator.manager.args.jupyterlabImage }}
        command:
        - /manager
        env:
        - name: DEPLOY
          value: DEBUG
        - name: ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: access_key
              name: cpod-info
        - name: CPOD_ID
          valueFrom:
            configMapKeyRef:
              key: cpod_id
              name: cpod-info
        image: {{ .Values.cpodoperator.manager.image }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cpod-controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: portalsynch
    app.kubernetes.io/created-by: cpodjob
    app.kubernetes.io/instance: portalsynch
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: cpodjob
    control-plane: portalsynch
  name: cpod-portalsynch
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: portalsynch
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: portalsynch
      labels:
        control-plane: portalsynch
    spec:
      containers:
      - env:
        - name: DEPLOY
          value: DEBUG
        - name: ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: access_key
              name: cpod-info
        - name: CPOD_ID
          valueFrom:
            configMapKeyRef:
              key: cpod_id
              name: cpod-info
        - name: STORAGECLASS
          valueFrom:
            configMapKeyRef:
              key: storage_class
              name: cpod-info
        - name: API_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: api_address
              name: cpod-info
        image: {{ .Values.portalsynch.image }}
        name: portalsynch
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: cpod-sa-portalsynch
      terminationGracePeriodSeconds: 10
{{- end }}
