apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches:
  - amd64
  operatingSystems:
  - arch: amd64
    type: linux
    id: ubuntu
    version: "20.04"
    osImage: Ubuntu 20.04.6 LTS
    repository:
      iso:
        # 将iso一起导出到artifact，离线部署依赖的操作系统相关package可直接从iso挂载获取
        localPath:
        url:
  kubernetesDistributions:
  - type: kubernetes
    version: v1.24.3
  components:
    helm:
      version: v3.9.0
    cni:
      version: v0.9.1
    etcd:
      version: v3.4.13
    containerRuntimes:
    - type: containerd
      version: 1.6.4
    crictl:
      version: v1.24.0
    # 开启harbor/docker-compose，用于离线部署时安装私有仓库
    docker-registry:
      version: "2"
    harbor:
      version: v2.4.1
    docker-compose:
      version: v2.2.2
  images:
  # 以下列表基于kubekey单独安装kubernetes后生成
  # 如需其他镜像可在此添加，离线部署时所有镜像将push到私有仓库
  - registry.cn-beijing.aliyuncs.com/kubesphereio/cni:v3.23.2
  - registry.cn-beijing.aliyuncs.com/kubesphereio/coredns:1.8.6
  - registry.cn-beijing.aliyuncs.com/kubesphereio/k8s-dns-node-cache:1.15.12
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.24.3
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controller-manager:v1.24.3
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controllers:v3.23.2
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-proxy:v1.24.3
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-scheduler:v1.24.3
  - registry.cn-beijing.aliyuncs.com/kubesphereio/node:v3.23.2
  - registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.7
  - registry.cn-beijing.aliyuncs.com/kubesphereio/pod2daemon-flexvol:v3.23.2
  - registry.cn-beijing.aliyuncs.com/kubesphereio/haproxy:2.3
  # 以下镜像用于 gpu operator 部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/metrics-server:v0.6.4
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/alpine-nginx:main
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/node-feature-discovery:v0.14.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/gpu-operator-validator:v23.6.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/gpu-operator:v23.6.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/container-toolkit:v1.13.4-ubuntu20.04
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/cuda:12.2.0-base-ubi8
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/dcgm-exporter:3.1.8-3.1.5-ubuntu20.04
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/k8s-device-plugin:v0.14.1-ubi8
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/driver:535.104.05-ubuntu20.04
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/gpu-feature-discovery:v0.8.1-ubi8
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/k8s-mig-manager:v0.5.3-ubuntu20.04
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/vgpu-device-manager:v0.2.3
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/k8s-driver-manager:v0.6.2
  # 以下镜像用于 network operator 部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/network-operator:v23.7.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/k8s-rdma-shared-dev-plugin:v1.3.2
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/plugins:v1.2.0-amd64
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/multus-cni:v3.9.3
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/whereabouts:v0.6.1-amd64
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/ipoib-cni:v1.1.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/mofed:23.07-0.5.0.0-ubuntu20.04-amd64
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/sriov-network-device-plugin:7e7f979087286ee950bd5ebc89d8bbb6723fc625
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
  # 以下镜像用于 kube-prometheus-stack 部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/alertmanager:v0.26.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/prometheus-operator:v0.68.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/prometheus:v2.47.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/k8s-sidecar:1.25.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/node-exporter:v1.6.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/grafana:10.1.4
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/bats:v1.4.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/kube-state-metrics:v2.10.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/prometheus-config-reloader:v0.68.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/sriov-network-operator:network-operator-23.7.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/infiniband-exporter:main
  # 以下镜像用于 training operator 部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/mpi-operator:master
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/training-operator:master
  # 以下镜像用于 juicefs-csi 部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/livenessprobe:v2.11.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/csi-node-driver-registrar:v2.9.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/csi-provisioner:v3.5.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/csi-resizer:v1.9.0
  # 以下镜像用于 rook-ceph operator 部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/ceph:v17.2.6
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/ceph:v1.12.5
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/cephcsi:v3.9.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/csi-provisioner:v3.5.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/csi-resizer:v1.8.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/csi-attacher:v4.3.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/csi-snapshotter:v6.2.2
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/csi-node-driver-registrar:v2.8.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/vc-controller-manager:latest
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/vc-webhook-manager:latest
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/vc-scheduler:latest
  # 以下镜像用于 loki-stack operator 部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/loki:2.6.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/promtail:2.8.3
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/bats:1.8.2
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/kube-rbac-proxy:0.15.0
  # 以下镜像用于 cpod operator 部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/cpodoperator:e81b699
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/portalsynch:e81b699
  # 以下镜像用于 kserve operator 部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/cert-manager-cainjector:v1.13.3
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/cert-manager-webhook:v1.13.3
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/cert-manager-controller:v1.13.3
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/cert-manager-acmesolver:v1.13.3
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/controller:v1.8.2
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/kube-webhook-certgen:v20230407
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/kserve-controller:v0.11.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/kube-rbac-proxy:v0.13.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/lgbserver:v0.11.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/mlserver:1.3.2c
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/paddleserver:v0.11.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/pmmlserver:v0.11.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/sklearnserver:v0.11.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/serving:2.6.2
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/torchserve-kfs:0.8.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/tritonserver:23.05-py3
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/xgbserver:v0.11.0
  # 以下镜像用于无代码微调、推理相关服务部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/kruise-manager:v1.5.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/ib:latest
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/mpi-pi:openmpi
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/pytorch-example:latest
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/modelscope_gpt3_1h1g1dp:latest
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/fastchat:v1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/vllm:latest
  # 以下镜像用于计费相关服务部署
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/opencost-ui:latest
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/kubecost-cost-model:latest
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/dashboard:v2.7.0
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/metrics-scraper:v1.0.8
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/tensorflow:latest
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/pulsar:2.8.2
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/etcd:3.5.5-r2
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/minio:RELEASE.2023-03-20T20-16-18Z
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/rag-service:v0.1.1
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/openchat:v0106
  - sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/llamafactory:latest
  registry:
    auths: {}
