# 跟蓝耘的 GPU 服务器宿主机上安装的驱动相匹配
# NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7
FROM nvidia/cuda:11.7.1-devel-ubuntu20.04

RUN apt-get update && apt-get install -y python3-pip
RUN apt-get install -y git

#安装ssh
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install vim openssh-server iputils-ping wget curl -y \
&& sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config \
&& echo "root:123456" | chpasswd

# 更换 Pip 源到国内的镜像源
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
# 更新 Pip 源之后，用 Python3 重新安装 Pip，并在之后用 Python3 调用 Pip 
RUN python3 -m pip install --no-cache-dir --upgrade pip

# 将当前目录的全部内容拷贝到容器镜像的 /workspace 目录
ADD . /workspace

# 将容器镜像的 /workspace 目录设置为容器镜像启动时的工作目录
WORKDIR /workspace

# 安装相应的 Python 包
RUN python3 -m pip install -r requirements.txt

#CMD sleep 3600
RUN mkdir -p /keys
RUN ssh-keygen -q -t rsa -N '' -f /keys/id_rsa 
