version: '3.3'
services:
  master:
          #build:
          #context: .
          #dockerfile: Dockerfile
    image: bert_deepspeed:v3
    container_name: bert_deepspeed
    ports:
      - "19010:22"
    networks:
      - my_network
    command: deepspeed --hostfile=dc_hostfile/hostfile --master_port 60000 train_bert_ds.py --checkpoint_dir ./ds_experiments
    #command: deepspeed --include=localhost:0  --master_port 60000 train_bert_ds.py --checkpoint_dir ./ds_experiments

  worker1:
    image: bert_deepspeed:v3
    container_name: bert_deepspeed
    ports:
      - "19011:22"
    depends_on:
      - master
    environment:
      - CUDA_VISIBLE_DEVICES=0
    networks:
      - my_network
  
  worker2:
    image: bert_deepspeed:v3
    container_name: bert_deepspeed
    ports:
      - "19012:22"
    depends_on:
      - master
    environment:
      - CUDA_VISIBLE_DEVICES=1
    networks:
      - my_network
networks:
    my_network:
