# permissions for end users to edit cpodjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cpodjob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cpodjob
    app.kubernetes.io/part-of: cpodjob
    app.kubernetes.io/managed-by: kustomize
  name: cpodjob-editor-role
rules:
- apiGroups:
  - cpod.sxwl.ai
  resources:
  - cpodjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.sxwl.ai
  resources:
  - cpodjobs/status
  verbs:
  - get
