# permissions for end users to view finetunes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: finetune-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cpodjob
    app.kubernetes.io/part-of: cpodjob
    app.kubernetes.io/managed-by: kustomize
  name: finetune-viewer-role
rules:
- apiGroups:
  - cpod.cpod
  resources:
  - finetunes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - finetunes/status
  verbs:
  - get
