---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - cpodjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - cpodjobs/finalizers
  verbs:
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - cpodjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - datasetstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - datasetstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - finetunes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - finetunes/finalizers
  verbs:
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - finetunes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - inferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - inferences/finalizers
  verbs:
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - inferences/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - jupyterlabs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - jupyterlabs/finalizers
  verbs:
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - jupyterlabs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - llamafactories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - llamafactories/finalizers
  verbs:
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - llamafactories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - modelstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - modelstorages/finalizers
  verbs:
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - modelstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - yamlresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpod.cpod
  resources:
  - yamlresources/finalizers
  verbs:
  - update
- apiGroups:
  - cpod.cpod
  resources:
  - yamlresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices/status
  verbs:
  - get
  - patch
  - update
