apiVersion: v1
kind: Pod
metadata:
  name: for-nccl-test
spec:
  runtimeClassName: nvidia
  restartPolicy: Never
  containers:
    - name: for-nccl-test
      image: swr.cn-east-3.myhuaweicloud.com/sxwl/for_nccl_test:latest
      resources:
        limits:
          nvidia.com/gpu: 2
      imagePullPolicy: IfNotPresent
      volumeMounts:
      # https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#sharing-data
      # 如果没有这句，NCCL的SHM通讯方式会出错
      - mountPath: /dev/shm
        name: cache-volume
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 1024Mi
      name: cache-volume
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
