# Codelint is in super-linter, this includes linters not supported
# in super linter, and custom ones developed in house.
name: Additional lint
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  query-changed-files:
    name: List changed files
    # This matches the dev_image and base image used in the code base.
    runs-on: ubuntu-22.04
    outputs:
      any_ui_changed: ${{ steps.ui-changed.outputs.any_changed}}
      any_src_changed: ${{ steps.src-changed.outputs.any_changed}}
      any_go_changed: ${{ steps.go-changed.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v3
        with:
          # Retrieve the preceding commit
          fetch-depth: 0
  container-image-rules-lint:
    name: Must use custom container image rules
    runs-on: ubuntu-latest
    needs: query-changed-files
    if: needs.query-changed-files.outputs.any_src_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      # Check that no one is using the native container_image rules
      - name: Custom container image rules
        run: .github/scripts/check_container_image_rules.sh
        shell: bash
  check-readme:
    name: Must have README.md
    runs-on: ubuntu-latest
    needs: query-changed-files
    if: needs.query-changed-files.outputs.any_src_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      # Check that all directories under src/ have a README.md
      - name: Check README.md
        run: .github/scripts/check_readme.sh
        shell: bash
  check-markdown-filenam:
    name: Markdown filename
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Check that all markdown filenames are uppercase
      - name: Check markdown files
        run: .github/scripts/check_markdown_filename.sh
        shell: bash
  check-todo:
    name: TODOs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: .github/scripts/check_todo.sh
        shell: bash
