name: Additional lint
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  check-markdown-filename:
    name: Markdown filename
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Check that all markdown filenames are uppercase
      - name: Check all
        run: .github/scripts/check_all.sh
        shell: bash
