name: Base Image Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/docker/**Dockerfile'

env:
    DOCKER_REGISTRY: sxwl-registry.cn-beijing.cr.aliyuncs.com
    NAMESPACE: sxwl-ai

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
            registry: ${{ env.DOCKER_REGISTRY }}
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push changed Docker images
        run: |
          changed_files=""
          if git rev-parse HEAD^ >/dev/null 2>&1; then
              changed_files=$(git diff --name-only HEAD^ HEAD | grep 'examples/docker/')
          else
              changed_files=$(git ls-tree --name-only -r HEAD | grep 'examples/docker/')
          fi
          for file in $changed_files; do
            if [[ $file == *.Dockerfile ]]; then
              image_name=$(basename $file .Dockerfile)
              tag=$(date +%Y-%m-%d)
              docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.NAMESPACE }}/${image_name}:v${tag} -f $file ./examples/docker
              docker push ${{ env.DOCKER_REGISTRY }}/${{ env.NAMESPACE }}/${image_name}:v${tag}
            fi
          done
