name: Bazel Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  query-changed-files:
    name: List changed files
    # This matches the dev_image and base image used in the code base.
    runs-on: ubuntu-22.04
    outputs:
      all: ${{ steps.src-changed.outputs.all_changed_files}}
      any_changed: ${{ steps.src-changed.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v3
        with:
          # Retrieve the preceding commit
          fetch-depth: 0
      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v35
        with:
          files: ./**
      - name: DEBUG print changed files under src/
        run: |
          echo ${{ steps.changed.outputs.all_changed_files }}
          echo ${{ steps.changed.outputs.any_changed }}

  build-and-test:
    name: Bazel build and test
    # This matches the dev_image and base image used in the code base.
    runs-on: ubuntu-22.04
    # require the first job to have ran
    needs: query-changed-files
    # only run there are changed files
    if: needs.query-changed-files.outputs.any_changed == 'true'
    steps:
      # TBA
