# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Build and Push Container Images

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  GHCR_REGISTRY: ghcr.io/${{ github.repository_owner }}
  DOCKER_HUB_REGISTRY: docker.io/tricorderobservability

jobs:
  build-and-push-images:
    name: Build and Push Container Images
    runs-on: ubuntu-latest
    container:
      image: docker.io/tricorderobservability/ci_image:202303180311
    timeout-minutes: 90
    permissions:
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - uses: bazelbuild/setup-bazelisk@v2
      - name: Build and push starship api-server image to Github Packages
        run: |
          .github/scripts/bazel.sh run --define=TAG=${{ inputs.tag }} --define=REGISTRY=${GHCR_REGISTRY} //src/api-server/cmd:push_api-server_image
          .github/scripts/bazel.sh run --define=TAG=${{ inputs.tag }} --define=REGISTRY=${DOCKER_HUB_REGISTRY} //src/api-server/cmd:push_api-server_image
          .github/scripts/bazel.sh run --define=TAG=${{ inputs.tag }} --define=REGISTRY=${GHCR_REGISTRY} //src/agent/cmd:push_agent_image
          .github/scripts/bazel.sh run --define=TAG=${{ inputs.tag }} --define=REGISTRY=${DOCKER_HUB_REGISTRY} //src/agent/cmd:push_agent_image

      # Below are for building and pushing mgmt-ui image
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: "ui"
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: run build # will run `yarn run build` command
          dir: "ui"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push GitHub package registry
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./ui/docker/Dockerfile
          context: ./ui
          tags: ${{ env.GHCR_REGISTRY }}/mgmt-ui:${{ inputs.tag }},${{ env.DOCKER_HUB_REGISTRY }}/mgmt-ui:${{ inputs.tag }}
