name: ChatUI Docker Build

on:
  pull_request:
    paths:
      - "chatui/Dockerfile"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./chatui
          file: ./chatui/Dockerfile
          push: false
          tags: chatui:pr-${{ github.event.pull_request.number }}
