name: CPodManager-CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cmd/**.go'
      - 'deployment/**Dockerfile'

env:
  DOCKERHUB_REPO: registry.cn-beijing.aliyuncs.com/sxwl-ai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'

      - name: Generate image tag
        run: echo COMMIT_ID=`git rev-parse --short HEAD` >> $GITHUB_ENV

      - name: Build and Push images
        run: |
          go build -v ./cmd/cpodmanager
          go build -v ./cmd/modeluploader
          docker build --tag ${{ env.DOCKERHUB_REPO }}/cpodmanager:${{ env.COMMIT_ID }} --file ./deployment/cpodmanager/Dockerfile .
          docker build --tag ${{ env.DOCKERHUB_REPO }}/modeluploader:${{ env.COMMIT_ID }} --file ./deployment/modeluploader/Dockerfile .
          docker push ${{ env.DOCKERHUB_REPO }}/cpodmanager:${{ env.COMMIT_ID }}
          docker push ${{ env.DOCKERHUB_REPO }}/modeluploader:${{ env.COMMIT_ID }}
