name: CPodManager-CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cmd/**.go'
      - 'deployment/**Dockerfile'

env:
  DOCKERHUB_REPO: registry.cn-beijing.aliyuncs.com/sxwl-ai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'

      - name: Build image
        run: |
          go build -v ./cmd/cpodmanager
          go build -v ./cmd/modeluploader

      - name: Push image
        run: |
          docker build --tag ${{ env.DOCKERHUB_REPO }}/cpodmanager:`git rev-parse --short HEAD` --file ./deployment/cpodmanager/Dockerfile .
          docker build --tag ${{ env.DOCKERHUB_REPO }}/modeluploader:`git rev-parse --short HEAD` --file ./deployment/modeluploader/Dockerfile .
          docker push ${{ env.DOCKERHUB_REPO }}/cpodmanager:`git rev-parse --short HEAD`
          docker push ${{ env.DOCKERHUB_REPO }}/modeluploader:`git rev-parse --short HEAD`
