name: Generate and Push SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SDK Version to Generate (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  generate-and-push-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install OpenAPI Generator CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Generate Python SDK
        run: |
          openapi-generator-cli generate \
          -i ./cmd/scheduler/sdk.json \
          -g python \
          -o /tmp/sxwl-python-sdk \
          --package-name sxwl_client \
          --additional-properties=packageVersion=${{ github.event.inputs.version }}

      - name: Checkout `sxwl-python-sdk` Repository
        uses: actions/checkout@v3
        with:
          repository: NascentCore/sxwl-python-sdk
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          persist-credentials: false
      
      - name: Copy Generated SDK to Target Repository
        run: |
          rsync -av --delete --exclude=".git" /tmp/sxwl-python-sdk/ .
          git add .
          git commit -m "Generated SDK for version ${{ github.event.inputs.version }}"
          git push
