name: sxcloud java CI

# 以下代表main分支有push
# 且aiadmin目录下（递归）java文件有更新或deployment/sxcloud目录下Dockerfile文件有更新时触发构建
on:
  push:
    branches: [ "main" ]
    paths:
      - 'aiadmin/**.java'
      - 'deployment/sxcloud/**Dockerfile'

env:
  DOCKERHUB_REPO: sxwl-registry.cn-beijing.cr.aliyuncs.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 拉取代码
    - uses: actions/checkout@v3

    # 安装jdk环境
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    # 构建代码
    - name: Build with Maven
      run: mvn -B package --file aiadmin/pom.xml
    # 设置COMMIT_ID环境变量，作为镜像tag
    - name: Generate image tag
      run: echo COMMIT_ID=`git rev-parse --short HEAD` >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # 登录镜像仓库
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKERHUB_REPO }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 构建镜像并推送到镜像仓库
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployment/sxcloud/Dockerfile
        push: true
        tags: sxwl-ai/sxcloud:${{ env.COMMIT_ID }}
