name: sxcloud java CI

# 以下代表main分支有push
# 且aiadmin目录下（递归）java文件有更新或deployment/sxcloud目录下Dockerfile文件有更新时触发构建
on:
  pull_request:
    branches:
      - main
    paths:
      - 'aiadmin/**'
      - 'deployment/sxcloud/**Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: sxwl-registry.cn-beijing.cr.aliyuncs.com
      NAMESPACE: sxwl-ai
      IMAGE_NAME: aiadmin
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
    # 拉取代码
    - uses: actions/checkout@v3

    # 安装jdk环境
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    # 构建代码
    - name: Build with Maven
      run: mvn -B package --file aiadmin/pom.xml

    - name: Extract version from PR comment
      id: extract_version
      run: |
        VERSION_TAG=$(echo "$PR_TITLE" | grep -oP 'build:\K.*' || echo "")
        echo "Version tag: $VERSION_TAG"
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

    - name: Check if version tag is set
      if: env.VERSION_TAG != ''
      run: echo "Version tag found, proceeding with build..."

    - name: Set up Docker Buildx
      if: env.VERSION_TAG != ''
      uses: docker/setup-buildx-action@v1

    # 登录镜像仓库
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 构建镜像并推送到镜像仓库
    - name: Build and push Docker image
      if: env.VERSION_TAG != ''
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployment/sxcloud/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}
